name: Pipeline [test -> build -> deploy]

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "flags/**"
  workflow_dispatch:
    inputs:
      additional_docker_tag:
        description: Additional docker tag that can be used to specify stable or testing tags
        required: false
        default: ""
        type: string
      push:
        description: Push docker image to registry flag
        required: true
        default: false
        type: boolean

permissions:
  contents: read

concurrency:
  # Only cancel in progress when on a branch - use SHA on main to ensure uniqueness.
  # This will allow multiple pipelines to run at the same time on main.
  # Note that two pipelines running within a few minutes of each other will cause issues with helm deploying to
  # a namespace, as the second one will not be able to get a lock as a deploy will be in progress.
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  OPA_VERSION: v1.15.1
  OPA_SHA256: 5c45f14a926b4b4b9e54d919fb76f9acb299ea1fdd1b204217a4eda5ba741ed1
  REGAL_VERSION: v0.39.0
  REGAL_SHA256: b4fd48ae33a85dc59352b32c34aaea104605d25a43680454f987682751595db9

jobs:
  helm_lint:
    strategy:
      matrix:
        environments: ["dev", "preprod", "prod"]
    name: helm lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_helm_lint.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: ${{ matrix.environments }}
  opa_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false
      - shell: bash
        run: |
          set -euo pipefail

          curl --fail --show-error --silent --location \
            --output opa \
            "https://github.com/open-policy-agent/opa/releases/download/${OPA_VERSION}/opa_linux_amd64"

          echo "${OPA_SHA256}  opa" | sha256sum --check --
          chmod 755 ./opa
          ./opa test flipt/policies/ -v
  opa_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false
      - shell: bash
        run: |
          set -euo pipefail

          curl --fail --show-error --silent --location \
            --output regal \
            "https://github.com/open-policy-agent/regal/releases/download/${REGAL_VERSION}/regal_Linux_x86_64"

          echo "${REGAL_SHA256}  regal" | sha256sum --check --
          chmod +x regal
          ./regal lint .

  build:
    name: Build docker image from hmpps-github-actions
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@v2 # WORKFLOW_VERSION
    with:
      docker_registry: "ghcr.io"
      registry_org: "ministryofjustice"
      additional_docker_tag: ${{ inputs.additional_docker_tag }}
      push: ${{ inputs.push || true }}
      docker_multiplatform: false
      file: flipt/Dockerfile
  deploy_dev:
    name: Deploy to the development environment
    needs:
      - build
      - helm_lint
      - opa_lint
      - opa_test
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: "dev"
      app_version: "${{ needs.build.outputs.app_version }}"
  deploy_preprod:
    name: Deploy to pre-production environment
    needs:
      - build
      - deploy_dev
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: "preprod"
      app_version: "${{ needs.build.outputs.app_version }}"
  deploy_prod:
    name: Deploy to production environment
    needs:
      - build
      - deploy_preprod
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: "prod"
      app_version: "${{ needs.build.outputs.app_version }}"
